FROM golang:1.15.12

ENV DISTRIBUTION_DIR /go/src/github.com/docker/distribution
ENV BUILDTAGS include_oss include_gcs

WORKDIR $DISTRIBUTION_DIR
COPY . $DISTRIBUTION_DIR

RUN GOOS=linux GOARCH=arm64 CGO_ENABLED=0 make PREFIX=/go clean binaries
