FROM photon:4.0

COPY ./make/photon/redis/redis-debuginfo-6.0.15-1.ph4.aarch64.rpm /redis/
COPY ./make/photon/redis/redis-6.0.15-1.ph4.aarch64.rpm /redis/

RUN tdnf install -y /redis/redis-debuginfo-6.0.15-1.ph4.aarch64.rpm /redis/redis-6.0.15-1.ph4.aarch64.rpm >> /dev/null \
    && rm -rf /redis \
    && tdnf clean all
